"""
VizForge Report Generator

Export data stories to various formats (Markdown, HTML, PDF).
NO API required - template-based generation!
"""

from enum import Enum
from typing import Optional
from pathlib import Path
from datetime import datetime

from .narrative_generator import DataStory


class ReportFormat(Enum):
    """Report output formats."""
    MARKDOWN = "markdown"
    HTML = "html"
    TEXT = "text"


class ReportGenerator:
    """
    Report generation and export.

    Converts DataStory to various output formats.

    Examples:
        >>> from vizforge.storytelling import generate_story, ReportGenerator
        >>>
        >>> story = generate_story(df)
        >>> generator = ReportGenerator(story)
        >>> generator.save("report.md", format=ReportFormat.MARKDOWN)
        >>> generator.save("report.html", format=ReportFormat.HTML)
    """

    def __init__(self, story: DataStory):
        """
        Initialize report generator.

        Args:
            story: DataStory object to export
        """
        self.story = story

    def to_markdown(self) -> str:
        """Convert story to Markdown format."""
        md_parts = []

        # Title
        md_parts.append(f"# {self.story.title}\n\n")

        # Metadata
        md_parts.append("---\n")
        md_parts.append(f"**Generated**: {self.story.metadata.get('generated_at', 'N/A')}\n\n")
        md_parts.append(f"**Dataset**: {self.story.metadata.get('rows', 0):,} rows, ")
        md_parts.append(f"{self.story.metadata.get('columns', 0)} columns\n\n")
        md_parts.append(f"**Insights**: {self.story.metadata.get('insights_count', 0)}\n")
        md_parts.append("---\n\n")

        # Executive Summary
        md_parts.append("## Executive Summary\n\n")
        md_parts.append(f"{self.story.summary}\n\n")

        # Full Narrative
        md_parts.append(self.story.narrative)

        # Recommendations
        if self.story.recommendations:
            md_parts.append("\n\n## Recommendations\n\n")
            for i, rec in enumerate(self.story.recommendations, 1):
                md_parts.append(f"{i}. {rec}\n")

        # Footer
        md_parts.append(f"\n\n---\n")
        md_parts.append(f"*Generated by VizForge Auto Data Storytelling*\n")

        return "".join(md_parts)

    def to_html(self) -> str:
        """Convert story to HTML format."""
        html_parts = []

        # HTML header
        html_parts.append("""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            line-height: 1.6;
            max-width: 900px;
            margin: 0 auto;
            padding: 20px;
            color: #333;
        }}
        h1 {{
            color: #2c3e50;
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #34495e;
            margin-top: 30px;
            border-bottom: 1px solid #ecf0f1;
            padding-bottom: 5px;
        }}
        .metadata {{
            background: #ecf0f1;
            padding: 15px;
            border-radius: 5px;
            margin: 20px 0;
        }}
        .summary {{
            background: #e8f6ff;
            padding: 20px;
            border-left: 4px solid #3498db;
            margin: 20px 0;
        }}
        .insight {{
            margin: 15px 0;
            padding: 15px;
            background: #f9f9f9;
            border-left: 3px solid #95a5a6;
            border-radius: 3px;
        }}
        .insight-title {{
            font-weight: bold;
            color: #2c3e50;
        }}
        .recommendation {{
            background: #fff3cd;
            padding: 10px;
            margin: 5px 0;
            border-left: 3px solid #ffc107;
            border-radius: 3px;
        }}
        .recommendations {{
            margin-top: 30px;
        }}
        .footer {{
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ecf0f1;
            color: #7f8c8d;
            text-align: center;
            font-size: 0.9em;
        }}
        ul {{
            list-style-type: none;
            padding-left: 0;
        }}
        li {{
            margin: 10px 0;
            padding-left: 30px;
            position: relative;
        }}
        li:before {{
            content: "▸";
            position: absolute;
            left: 10px;
            color: #3498db;
        }}
    </style>
</head>
<body>
""".format(title=self.story.title))

        # Title
        html_parts.append(f"    <h1>{self.story.title}</h1>\n\n")

        # Metadata
        html_parts.append("    <div class='metadata'>\n")
        html_parts.append(f"        <strong>Generated:</strong> {self.story.metadata.get('generated_at', 'N/A')}<br>\n")
        html_parts.append(f"        <strong>Dataset:</strong> {self.story.metadata.get('rows', 0):,} rows, ")
        html_parts.append(f"{self.story.metadata.get('columns', 0)} columns<br>\n")
        html_parts.append(f"        <strong>Insights Discovered:</strong> {self.story.metadata.get('insights_count', 0)}\n")
        html_parts.append("    </div>\n\n")

        # Executive Summary
        html_parts.append("    <div class='summary'>\n")
        html_parts.append("        <h2>Executive Summary</h2>\n")
        html_parts.append(f"        <p>{self.story.summary}</p>\n")
        html_parts.append("    </div>\n\n")

        # Convert markdown narrative to HTML
        narrative_html = self._markdown_to_html(self.story.narrative)
        html_parts.append(f"    <div class='narrative'>\n{narrative_html}\n    </div>\n\n")

        # Recommendations
        if self.story.recommendations:
            html_parts.append("    <div class='recommendations'>\n")
            html_parts.append("        <h2>Recommendations</h2>\n")
            html_parts.append("        <ul>\n")
            for rec in self.story.recommendations:
                html_parts.append(f"            <li class='recommendation'>{rec}</li>\n")
            html_parts.append("        </ul>\n")
            html_parts.append("    </div>\n\n")

        # Footer
        html_parts.append("    <div class='footer'>\n")
        html_parts.append("        <p>Generated by <strong>VizForge Auto Data Storytelling</strong></p>\n")
        html_parts.append("    </div>\n")

        # Close HTML
        html_parts.append("</body>\n</html>")

        return "".join(html_parts)

    def to_text(self) -> str:
        """Convert story to plain text format."""
        text_parts = []

        # Title
        text_parts.append("=" * 80 + "\n")
        text_parts.append(self.story.title.center(80) + "\n")
        text_parts.append("=" * 80 + "\n\n")

        # Metadata
        text_parts.append(f"Generated: {self.story.metadata.get('generated_at', 'N/A')}\n")
        text_parts.append(f"Dataset: {self.story.metadata.get('rows', 0):,} rows, ")
        text_parts.append(f"{self.story.metadata.get('columns', 0)} columns\n")
        text_parts.append(f"Insights: {self.story.metadata.get('insights_count', 0)}\n\n")
        text_parts.append("-" * 80 + "\n\n")

        # Executive Summary
        text_parts.append("EXECUTIVE SUMMARY\n")
        text_parts.append("-" * 80 + "\n")
        text_parts.append(f"{self.story.summary}\n\n")

        # Remove markdown formatting from narrative
        narrative_text = self._markdown_to_text(self.story.narrative)
        text_parts.append(narrative_text)

        # Recommendations
        if self.story.recommendations:
            text_parts.append("\n\nRECOMMENDATIONS\n")
            text_parts.append("-" * 80 + "\n")
            for i, rec in enumerate(self.story.recommendations, 1):
                text_parts.append(f"{i}. {rec}\n")

        # Footer
        text_parts.append("\n" + "=" * 80 + "\n")
        text_parts.append("Generated by VizForge Auto Data Storytelling\n")
        text_parts.append("=" * 80 + "\n")

        return "".join(text_parts)

    def save(self, filepath: str, format: Optional[ReportFormat] = None) -> str:
        """
        Save report to file.

        Args:
            filepath: Output file path
            format: Output format (auto-detected from extension if not provided)

        Returns:
            Path to saved file
        """
        path = Path(filepath)

        # Auto-detect format from extension
        if format is None:
            ext = path.suffix.lower()
            if ext == '.md':
                format = ReportFormat.MARKDOWN
            elif ext == '.html':
                format = ReportFormat.HTML
            elif ext == '.txt':
                format = ReportFormat.TEXT
            else:
                format = ReportFormat.MARKDOWN  # Default

        # Generate content
        if format == ReportFormat.MARKDOWN:
            content = self.to_markdown()
        elif format == ReportFormat.HTML:
            content = self.to_html()
        elif format == ReportFormat.TEXT:
            content = self.to_text()
        else:
            raise ValueError(f"Unsupported format: {format}")

        # Save to file
        path.write_text(content, encoding='utf-8')

        return str(path)

    def _markdown_to_html(self, markdown: str) -> str:
        """Convert basic markdown to HTML."""
        html = markdown

        # Headers
        html = html.replace('### ', '<h3>').replace('\n\n', '</h3>\n\n')
        html = html.replace('## ', '<h2>').replace('\n\n', '</h2>\n\n')
        html = html.replace('# ', '<h1>').replace('\n\n', '</h1>\n\n')

        # Bold
        import re
        html = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html)

        # Italic
        html = re.sub(r'\*(.+?)\*', r'<em>\1</em>', html)

        # Paragraphs
        html = html.replace('\n\n', '</p>\n<p>')
        html = '<p>' + html + '</p>'

        # Lists
        html = re.sub(r'(\d+)\. ', r'<li>', html)

        return html

    def _markdown_to_text(self, markdown: str) -> str:
        """Convert markdown to plain text."""
        import re
        text = markdown

        # Remove markdown formatting
        text = re.sub(r'#{1,6} ', '', text)  # Headers
        text = re.sub(r'\*\*(.+?)\*\*', r'\1', text)  # Bold
        text = re.sub(r'\*(.+?)\*', r'\1', text)  # Italic
        text = re.sub(r'`(.+?)`', r'\1', text)  # Code

        return text


# ==================== Convenience Function ====================

def generate_report(
    story: DataStory,
    filepath: str,
    format: Optional[ReportFormat] = None
) -> str:
    """
    Generate and save report (one-liner!).

    Args:
        story: DataStory object
        filepath: Output file path
        format: Output format (auto-detected if not provided)

    Returns:
        Path to saved file

    Examples:
        >>> from vizforge.storytelling import generate_story, generate_report
        >>>
        >>> story = generate_story(df)
        >>>
        >>> # Save as Markdown
        >>> generate_report(story, "report.md")
        >>>
        >>> # Save as HTML
        >>> generate_report(story, "report.html")
        >>>
        >>> # Save as plain text
        >>> generate_report(story, "report.txt")
    """
    generator = ReportGenerator(story)
    return generator.save(filepath, format=format)
