"""
VizForge - Production-grade data visualization library with zero AI dependencies.

Create beautiful, interactive visualizations with a single line of code.

v0.4.0: Now with 40+ chart types! (12 2D + 6 3D + 5 Geo + 6 Network + 5 Real-time + 9 Stats + 5 Advanced)
"""

from .version import __version__

from .core import (
    BaseChart,
    Theme,
    get_theme,
    set_theme,
    register_theme,
    list_themes,
)

# Import all 40+ chart types
from .charts import (
    # 2D Chart Classes
    LineChart,
    BarChart,
    AreaChart,
    ScatterPlot,
    PieChart,
    Heatmap,
    Histogram,
    Boxplot,
    RadarChart,
    WaterfallChart,
    FunnelChart,
    BubbleChart,
    # 3D Chart Classes
    SurfacePlot,
    Scatter3D,
    Mesh3D,
    VolumePlot,
    ConePlot,
    IsosurfacePlot,
    # Geographic Chart Classes
    ChoroplethMap,
    ScatterGeoMap,
    LineGeoMap,
    DensityGeoMap,
    FlowMap,
    # Network Chart Classes
    NetworkGraph,
    SankeyDiagram,
    TreeDiagram,
    IcicleDiagram,
    Dendrogram,
    ClusterHeatmap,
    # Real-time Chart Classes
    StreamingLine,
    LiveHeatmap,
    AnimatedScatter,
    AnimatedBar,
    AnimatedChoropleth,
    # Statistical Chart Classes
    ViolinPlot,
    KDEPlot,
    KDE2D,
    RegressionPlot,
    CorrelationMatrix,
    ROCCurve,
    MultiROCCurve,
    FeatureImportance,
    PermutationImportance,
    # Advanced Chart Classes
    Treemap,
    Sunburst,
    ParallelCoordinates,
    ContourPlot,
    FilledContour,
    # 2D Functions
    line,
    bar,
    area,
    scatter,
    pie,
    donut,
    heatmap,
    histogram,
    boxplot,
    radar,
    waterfall,
    funnel,
    bubble,
    # 3D Functions
    surface,
    scatter3d,
    mesh3d,
    volume,
    cone,
    isosurface,
    # Geographic Functions
    choropleth,
    scattergeo,
    linegeo,
    densitygeo,
    flowmap,
    # Network Functions
    network_graph,
    sankey,
    tree,
    icicle,
    dendrogram,
    cluster_heatmap,
    # Real-time Functions
    streaming_line,
    live_heatmap,
    animated_scatter,
    animated_bar,
    animated_choropleth,
    # Statistical Functions
    violin,
    kde,
    kde2d,
    regression,
    correlation_matrix,
    roc_curve_plot,
    multi_roc_curve,
    feature_importance,
    permutation_importance,
    # Advanced Functions
    treemap,
    sunburst,
    parallel_coordinates,
    contour,
    filled_contour,
)

__all__ = [
    # Version
    "__version__",
    # Core
    "BaseChart",
    "Theme",
    "get_theme",
    "set_theme",
    "register_theme",
    "list_themes",
    # 2D Chart Classes
    "LineChart",
    "BarChart",
    "AreaChart",
    "ScatterPlot",
    "PieChart",
    "Heatmap",
    "Histogram",
    "Boxplot",
    "RadarChart",
    "WaterfallChart",
    "FunnelChart",
    "BubbleChart",
    # 3D Chart Classes
    "SurfacePlot",
    "Scatter3D",
    "Mesh3D",
    "VolumePlot",
    "ConePlot",
    "IsosurfacePlot",
    # Geographic Chart Classes
    "ChoroplethMap",
    "ScatterGeoMap",
    "LineGeoMap",
    "DensityGeoMap",
    "FlowMap",
    # Network Chart Classes
    "NetworkGraph",
    "SankeyDiagram",
    "TreeDiagram",
    "IcicleDiagram",
    "Dendrogram",
    "ClusterHeatmap",
    # Real-time Chart Classes
    "StreamingLine",
    "LiveHeatmap",
    "AnimatedScatter",
    "AnimatedBar",
    "AnimatedChoropleth",
    # Statistical Chart Classes
    "ViolinPlot",
    "KDEPlot",
    "KDE2D",
    "RegressionPlot",
    "CorrelationMatrix",
    "ROCCurve",
    "MultiROCCurve",
    "FeatureImportance",
    "PermutationImportance",
    # Advanced Chart Classes
    "Treemap",
    "Sunburst",
    "ParallelCoordinates",
    "ContourPlot",
    "FilledContour",
    # 2D Functions
    "line",
    "bar",
    "area",
    "scatter",
    "pie",
    "donut",
    "heatmap",
    "histogram",
    "boxplot",
    "radar",
    "waterfall",
    "funnel",
    "bubble",
    # 3D Functions
    "surface",
    "scatter3d",
    "mesh3d",
    "volume",
    "cone",
    "isosurface",
    # Geographic Functions
    "choropleth",
    "scattergeo",
    "linegeo",
    "densitygeo",
    "flowmap",
    # Network Functions
    "network_graph",
    "sankey",
    "tree",
    "icicle",
    "dendrogram",
    "cluster_heatmap",
    # Real-time Functions
    "streaming_line",
    "live_heatmap",
    "animated_scatter",
    "animated_bar",
    "animated_choropleth",
    # Statistical Functions
    "violin",
    "kde",
    "kde2d",
    "regression",
    "correlation_matrix",
    "roc_curve_plot",
    "multi_roc_curve",
    "feature_importance",
    "permutation_importance",
    # Advanced Functions
    "treemap",
    "sunburst",
    "parallel_coordinates",
    "contour",
    "filled_contour",
]
